export const ADD_QUESTION="ADD_QUESTION";
export const DELETE_QUESTION="DELETE_QUESTION";
export const EDIT_QUESTION="EDIT_QUESTION";
export const SHOW_QUESTION="SHOW_QUESTION";

export const UPDATE_QUESTION="UPDATE_QUESTION";
export const CHANGE_COLOR="CHANGE_COLOR";
export const CHANGE_SCORE="CHANGE_SCORE";
export const CHANGE_TIME="CHANGE_TIME";

export const INIT_QUESTIONS = "INIT_QUESTIONS";
export const USER_ANS_LIST = "USER_ANS_LIST";
export const UPDATE_ANS_LIST = "UPDATE_ANS_LIST";
export const SET_TEST_SCORE_ZERO = "SET_TEST_SCORE_ZERO";
export const SET_TEST_SCORE = "SET_TEST_SCORE";

export const FETCH_QUESTIONS_START = "FETCH_QUESTIONS_START";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_FAIL = "FETCH_QUESTIONS_FAIL";
export const FETCH_COLOR_SUCCESS = "FETCH_COLOR_SUCCESS";
export const FETCH_COLOR_FAIL = "FETCH_COLOR_FAIL";
export const FETCH_SCORE_SUCCESS = "FETCH_SCORE_SUCCESS";
export const FETCH_SCORE_FAIL = "FETCH_SCORE_FAIL";
export const FETCH_TIME_SUCCESS = "FETCH_TIME_SUCCESS";
export const FETCH_TIME_FAIL = "FETCH_TIME_FAIL"

