export const ADD_QUESTION="ADD_QUESTION";
export const DELETE_QUESTION="DELETE_QUESTION";
export const EDIT_QUESTION="EDIT_QUESTION";
export const SHOW_QUESTION="SHOW_QUESTION";

export const UPDATE_QUESTION="UPDATE_QUESTION";
export const CHANGE_COLOR="CHANGE_COLOR";
export const CHANGE_SCORE="CHANGE_SCORE";
export const CHANGE_TIME="CHANGE_TIME";
